language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: PHcO+D8xySM53rzHhKSX/kBqxdHzZ0ZVKxFnKEDGqViidQJhw9oXXCTEsT6Px06YqTEqmcfi4kRWPTI/LhpJQpM4Ri8Bj7zWsE7lLN3Ydizgiaf2O2Wv07pulIQWAccN2n8AD4HOK5lmx3u8tbu5FozhKrcHUT5ZD1LqMs7wLEtQ8f9rR81Qg83Bkg/Ro1KjCaa3cPtPQSjC/YGRA1tCgHWYjRu1DirU7KgQ6HUjNjsIQ3tHbfsC8ljEWNP2tiuI1YkRZiXyLlD6RNXeB8GprUq9T7CQZ+SeAx5Qm5lvkKIifFGZr+cZgsiVIfwDvU1N014b/HyY7S8/k3rZq3gwTR1qFL4DiVO1cFFn2SiUOdmK2ndgl+10K9WMcW8CYhAed9771m6wLwKlDcYX1boPle9RayJErY319XRkvdgWGFDNIoH6n16M0upifKr92VrX4hp2ufTdkvNVfxBJO03uNTdy+Ax9t2J3+nvNygJf7rUrYd9S+7adVuc//EoPfb67kTBU8vDMmtPjyMBc56EbvVbvd5GQZACKK5Ei1EMOlyVC3hCef85zpqwkXO+Qv5hvGuZ4YvlFr5pZzpZJ1ndOOYIMZPy+gxB754VsLLzmZiKi/W4yGp47Icsb3vHhKwip0oq5tzazBlqZFpjjVBM7xwRjDrj5treghJxG9Fssvy8=
  app: btb-graphql
  on:
    repo: brentguistwite/BTB-GraphQL
