language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ftIjgo/JH6mDqgWVpmHGFYeJdAszb7rdYc8iucyxQRO8rxvW6LXdB4CJoV9mySBfxRkss3CS4MGniUrtaq5CEgI/7pCwiqya6nsFS2VoR73ze9Br0UvLVkQCARlnkFZGB2bY7mUjaSMwy5lnnfvHm5YI/tKAQyA/1ehpfoKNn37O9Zuh1pjII+UX5QnbJRyU19xno3SxFwWqTZuT6ZJcPEJ7O8sdNoYULCQWSfn0nMRmFepQ8l07sSf1ErfPoJERcdJUhRCBB9v985lUXcD2DdR5Hgp5r2vKY8D8te1izpuPAeGDAmllXsq3/csokkNTjHpK90a6L/7usd9ph8fwXOMwDNwIz9gFt2unuvRD4mYFmJKKzsI+w9Ii7b604ZPf2Jjj5lOWmRi8QpDXDCZDtf9JWiOyxjCih4EAB2ykJgYdNkvFWa/3OfpDsKOS+2lN4RxZfDdsY+8uVcRDVcFWTxwh1LuUY+1KBwyoWxTVmnFdIagP5ph5hJ4oGAxslHEA1O9Zo5uBa68fF9QJGRng9VK0x/Ss8QAdHsHVEdklBznZQBaGntzFAbh/L7q/dS7cgeMniaU6JJ2KL0SdiMbUYo8t0UVGuxkvZTlIsWNdbMCcbhc9GL6R5k/WcARzzi3jzIQK8tX61LkjddYhSTP6ZCmYMWkkYSlm8tbj6sHyirg=
  app: stark-sierra-32501
  on:
    repo: thinkful-ei17/spaced-rep-server
env:
  global:
    secure: x726NroEtkAgT2J283eW661Eou77JmVzTi2GYwfnfn0f0C1/aWY8qawQVVGaCfUleSAY1YdjEPJoIF+zxxkbSwKSh5MUkO/PcKhzQVIkq97kIhtRkTmwfUU03gK4RXKBG+fSq+ejxRHK2G70Lt6SaF8s1/PNfKY2lYJocBczLuk8zW/uDJYCz45ZMExvzUKcZcDMSTpRzCoKRvJt36y8Wo8Ps1FWgIRYJQHlpclZxkQGvAGS53maLTZIjIahxa+XJKIg3ed1K5oD+Xq7UBIVZ+JQyHUUHIgBB8DYbzujAdaCDUB5NduWW7fV+xSxEEeNkDin80UY1loUUxtZ87C+RiCN/SIJ8GIs8tLWcinZX7k73dl4x3Smy/vM9/2One84HPxc5/mve6fAqLjIJQ61aH2fDR1sx59kXpKjlNaZ7pDgVoxoB3KUJMLJPJf9z/lzze1s7r2RPRyFMK06TvOrEFnDiT+kGRVq5oow74+IV0sOuLTFPZ5BQ/XjVVn3QXTqmciBSXwQZMEH4UrVdv0rJ3aqSyEI+Ve0PHb4NTlRRV4ivTGSYidHpErZBisy/3/ZJvKrbU6aBY3vCkmU88gnJwNKnLshlNimRYWdbkqKD/9u+wdi7rGVltekO6v7eUQddaTj5Fxrx9WlpHmc5oVykXrL5w+R4B02iY4RfoW3o5E=
